### ISSUE TITLE
definitions stopped showing up!

### ISSUE THREAD

**Issue by jugurtha6656** [PabloRomanH/zhongzhong#32]
instead there are these squiggly lines ;(

![wechat image_20180306202929](https://user-images.githubusercontent.com/34329649/37032336-1b86c6a0-217d-11e8-9c8e-0173470ae310.jpg)
really love the app keep it up! 
thank so much--jordan

**Comment by PabloRomanH** [comment]
It seems like you have enabled Zhuyin. You can go to Preferences, disable "Show Zhuyin (Bopomofo)" and enable "Show Definitions". You can also enable Pinyin there.

Alternatively, when the popup is showing try pressing the keys D, P and Z on your keyboard to achieve the same result.

**Comment by jugurtha6656** [comment]
whoops! figured it was something dumb i did.

Really appreciate the work you've put in on this all the best. Anywhere I
could donate?

**Comment by PabloRomanH** [comment]
Sure! Paypal to: sepharad@gmail.com
Thank you!
