### ISSUE TITLE
Allow Disabling Skritter Shortcut

### ISSUE THREAD

**Issue by mcmar** [PabloRomanH/zhongzhong#43]
Currently, it's not possible to disable the Skritter shortcut 's'. This is unfortunate as Language Learning with Netflix also uses 's' as the shortcut for repeating a subtitle.  Other shortcuts already have options to be enabled/disabled, but 's' has sadly been overlooked.

**Comment by PabloRomanH** [comment]
Let me take some time this weekend to look at this!

**Comment by mcmar** [comment]
Thanks @PabloRomanH 
I already submitted a pull request where I add a `disabled` option to the existing Skritter domain dropdown and slightly modify the copy to make it clear that you can disable it. If that looks good, then please feel free to merge and deploy when you get the chance. If you'd prefer, I can also easily create a separate checkbox to disable it as well. I figured this was a bit clearer instead of having a checkbox that effectively overrides the Skritter domain.

**Comment by mcmar** [comment]
Also, I of course tested the pull request in developer mode before and after to ensure that the existing Skritter functionality continues to work 100% as expected.

**Comment by mcmar** [comment]
Hey @PabloRomanH, would you mind doing a deploy to the Chrome store? It looks like the last update was Dec 2, 2019. Thank you!

**Comment by PabloRomanH** [comment]
Okay, I've submitted it with the last version of the dictionary. It says that they may take a few days or weeks to review it, though.
