### ISSUE TITLE
Doesn't seem to work on .txt files opened in chrome

### ISSUE THREAD

**Issue by alexkassil** [PabloRomanH/zhongzhong#53]
Hello! Love this and recently switched over from Zhongwen. When opening a .txt file in chrome, I cannot get ZhongZhong to work even though Zhongwen works.

I am not too familiar with javascript, but my best is guess is https://github.com/PabloRomanH/zhongzhong/blob/07c775706155d6a944365ea07586007c8c236b03/content.js#L919 here one could add something like `ev.target.nodeName == 'PRE'` since for a textfile opened it chrome it just becomes a big preformatted page of just text. 

I was trying to build locally to fix myself, but got stuck in the step after running `python index.py`, unsure how to find what was unpacked and load it into chrome.

**Comment by PabloRomanH** [comment]
I've tried it out and it seems to be working fine. Both Zhongwen and Zhongzhong behave exactly the same.
They work on TXT files that have been loaded from a URL.
When opening local files, neither Zhongwen nor Zhongzhong work unless you go to Extensions -> Zhongzhong -> Details -> Allow access to file URLs.

Closing.
