### ISSUE TITLE
Add Definitions for Redirected Entries

### ISSUE THREAD

**Issue by kumar-ish** [PabloRomanH/zhongzhong#59]
[Cross-posting from the Zhongwen github repo so the UI for the popup is different, but I've started using zhongzhong now and the same thing occurs in the zhongzohong UI]

Hi. Occasionally I come across a definition like "嘴硬心軟" (see screenshot) which just redirects to another definition through the extension. I think it would be good to show the redirected definition (perhaps indented under the suggestion to redirect) instead of having to manually find it on another website / on CEDICT. Perhaps this can be optionally enabled as an experiment on one of the extension options, just in case there's any edge cases that we don't consider. I'm happy to code this up and go through the review process as you see fit.

<img width="436" alt="image" src="https://github.com/cschiller/zhongwen/assets/47245900/9dd17f73-e640-4dc1-bce4-8747d8bed0f2">

**Comment by PabloRomanH** [comment]
Have you tried it? This should already be working. If it doesn't work with
some words then it means there's one more syntax for redirects that we
haven't considered and we should add it to the current ones.

2023年7月10日(月) 14:52 kumar-ish ***@***.***>:

**Comment by kumar-ish** [comment]
I was being silly, sorry 😓 -- I didn't notice the redirected definition at the bottom. Thank you!
