### ISSUE TITLE
Character decomposition feature

### ISSUE THREAD

**Issue by tomatoburnedout** [PabloRomanH/zhongzhong#62]
Hello,
I wanted to know if there is an option to look up characters by radicals, e.g. for both 不  or  木 it finds  杯 , like crtl+f . 
Also it would be great if it works with google docs. 

If you don't plan to make this change or know where I can find the solution please let me know
Thanks

**Comment by PabloRomanH** [comment]
This is a dictionary that translates highlighted words. There are no plans of adding word lookup functionality. I'm sure you can find regular dictionaries that can do that.

**Comment by benlieb** [comment]
This might have what you looking for https://chromewebstore.google.com/detail/chinese-console-popup-dic/mekipefdgdacoicbibojhhjppiiaoidp?pli=1

**Comment by tomatoburnedout** [comment]
> This might have what you looking for https://chromewebstore.google.com/detail/chinese-console-popup-dic/mekipefdgdacoicbibojhhjppiiaoidp?pli=1

Thank you very much! I'll try it out
